### ISSUE TITLE
Landing page and form for Draft Id or Slug

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/hashnode-preview#16]
User Stories:

1. We would like to have a landing page at `https://preview.freecodecamp.org`. 
2. Users would be able to enter a Hashnode Draft Id, example: `66450fc26022973650d2408a` 
3. Or a slug, example: `quincy-interviews-colby-fayock-dev-designer-male-model-prolific-fcc-contributor-podcast-128` into a one-liner input field. 
4. Clicking a "Preview Article" button should take them to the `/:idOrSlug` path, i.e `https://preview.freecodecamp.org/quincy-interviews-colby-fayock-dev-designer-male-model-prolific-fcc-contributor-podcast-128`

Additionally, the page should have a heading: "Hashnode Preview for freeCodeCamp Developer News" and a description that can be picked from the readme:

<img width="932" alt="image" src="https://github.com/freeCodeCamp/hashnode-preview/assets/1884376/d7f60cb3-805b-453d-9fe4-8af2114e6556">

```[tasklist]
### Tasks
- [ ] Rename the `src/routes/index.js` to `src/routes/routes.js`
- [ ] Update the reference to the above file reference in `src/server.js`
- [ ] Rename the `src/templates/index.njk` to `src/templates/post.njk` for better context.
- [ ] Update the reference to the above file in the `routes.js`
- [ ] Create a new `src/templates/home.njk` for the landing page (can copy over the `error.njk`) as staring point.
- [ ] Add a new route near the top of the routes `src/routes/route.js` for the `/` path for rendering the landing page. The order matters.
- [ ] Create the form as per the user-stories.
- [ ] Additionally add the heading and description as mentioned previously.
```
